### ISSUE TITLE
Hello ! Please update OC to 0.5.6 

### ISSUE THREAD

**Issue by vnVyanz** [alkalim/ryzen-catalina#1]
Hello.
Thank for sharing your config for hacktintosh using Opencore on Asrock B450M Pro 4.
I am using it and it very helpfull for me to using lastest catalina on my system.
I am using  Asrock B450M Pro4, Ryzen 5 2600 and AMD RX56, this boot flag is good for me without any problem with sleep and wake.
Hope it usefull for you: keepsyms=1 debug=0x100 npci=0x2000 alcid=5 darkwake=8

alcid=5  for audio

and last, please update Opencore 0.5.6

Thank you.

**Comment by alkalim** [comment]
Thanks for sharing your settings, this is very useful info! Will update soon

**Comment by vnVyanz** [comment]
Thank you.

**Comment by alkalim** [comment]
Updated to OC 0.5.6.

darkwake=8 didn't do the trick for me neither on 0.5.5 nor on 0.5.6 (black screen but PC still working). Then I found [this thread](https://www.insanelymac.com/forum/topic/342002-darkwake-on-macos-catalina-boot-args-darkwake8-darkwake10-are-obsolete/).

**Comment by vnVyanz** [comment]
Hello. Thank you for the update OC to 0.5.6.
darkwake=8 working fine for me when usb 3.0 do not use any device.
I am using only usb 2.0 port, and sleep, awake fine on OC 0.5.5 or 0.5.6.
