### ISSUE TITLE
Just found this repo, altho I had my own

### ISSUE THREAD

**Issue by dr03m** [alkalim/ryzen-catalina#2]
Just found this repo when searching for hackintoshes like mine. 

https://github.com/dr03m/ASRock-B450M-Pro4-Hackintosh

Cheers!

**Comment by dr03m** [comment]
Nevermind, made it private under the request of r/hackintosh. 

I will be USB Map tho. If you want the repo, lmk.

**Comment by alkalim** [comment]
Good to know, thanks! I'm especially interested in your USB2.0 :)

**Comment by dr03m** [comment]
Made it private under the request of the Hackintosh community, since people benefit better to follow the guide instead of downloading a random EFI folder and wonder why somethings not working.

You can still find the USB patches [here](https://github.com/dr03m/ASRock-B450M-Pro4-USB-Patch)

**Comment by alkalim** [comment]
Thanks, will definitely try these! 

> since people benefit better to follow the guide instead of downloading a random EFI folder

I couldn't agree more. The purpose of my repo is mainly the guide (reasonably detailed for an average user), because I found it's pretty difficult to start from scratch without reading a ton of documents and posts first. The learning curve's too steep.
