### ISSUE TITLE
Error on select USB

### ISSUE THREAD

**Issue by Danhebanjin** [alkalim/ryzen-catalina#3]
Hi, thanks for sharing.

I have a small problem, and that is that when selecting my usb drive it gives me the following error, I am somewhat unskilled in this I hope it can help me 

![1db77408-bdff-49d5-98d1-9428f4aa922f](https://user-images.githubusercontent.com/47934096/86539247-99b51080-bec0-11ea-9d20-86485730ee23.jpg)

my config:
Ryzen 7 1700
Msi Gamingo Pro Carbon X370
Msi Vega 56 Airboost 8Gb OC
Corsair Vengance RGB 2X8 3000Mhz

**Comment by alkalim** [comment]
Hi,
I'm no expert either, but as your error message indicates - Info.plist is not found in your OpenCore Kexts/Lilu.kext/Contents folder. This can be either a file copy error (unlikely) or you have forgotten to copy Kexts/Lilu.kext or Kexts folder. Hope this helps :)
