### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cbezerra7** [alkalim/ryzen-catalina#4]
I have same motherboard and cpu. I can’t get mine to boot. What am I doing wrong? Can you share your efi and is there any changes to my bios settings?

**Comment by alkalim** [comment]
I recall I needed to reset my BIOS to default settings at some point (perhaps, before the installation), so try to reset and then install. I don't remember setting any obscure options in the BIOS, but you may want to look here https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html#amd-bios-settings and verify your BIOS settings match OpenCore expectations.

My EFI is right here in this repo, look into EFI folder. Also, are you sure you boot your USB key in EFI mode? My boot menu shows both legacy and EFI modes for removable media so it's easy to miss the proper menu item.

Please let me know if you had to do any additional steps to get it working so I can update the guide accordingly.
