### ISSUE TITLE
Compatibility with ASRock B450M Pro4-F and Ryzen 5 3400G

### ISSUE THREAD

**Issue by gopinet** [alkalim/ryzen-catalina#7]
Hi @alkalim, It will be that your configuration is compatible with ASRock B450M Pro4-F and Ryzen 5 3400G, thanks!!

**Comment by alkalim** [comment]
Hi, Pro4-F will likely work as there are only minor differences with Pro4 in terms of ports. Not sure about 3400G though. It might work provided that you also have a "normal" GPU, but you will almost certainly experience audio issues, as this build doesn't deal with AMD APU audio glitches in any way. You can ask in amd-osx forum to be sure.

Please report back if you try this build so I can update the guide accordingly.
